### ISSUE TITLE
[Feature request] checkboxes for each step

### ISSUE THREAD

**Issue by Gvanderl** [CraftySalamander/RTS_Overlay#1]
Hey, love this tool and I was wondering: 
Would it be possible to ass checkboxes that will cross-out/grey the steps so it's easier to know where you are ? 
Thanks !

**Comment by CraftySalamander** [comment]
Hi. Nice that you love the tool!

I am not sure I understand your feature request.
Build orders are typically split in many steps, and you can switch between them (with the overlay buttons or hotkeys).

So, to know where you are on the build order step, you just have to look at the current panel description (one panel description per step).
Usually, there are no more than 3 actions to perform per step, for which having checkboxes should not be very useful.

Could you elaborate more on your idea? Maybe share a specific example?
Also, small question, do you use it for AoE2 or AoE4?

**Comment by Gvanderl** [comment]
I'm using it with aoe2. I was thinking of putting checkboxes for what ou call  "actions", I posted this when I started using this mod but using it more, I realized that this feature isn't that necessary. As you said, there aren't many actions per step and it takes APM away from your game if you have to check the steps. 

I was thinking though that it could be useful to keep track of villagers per source of food. For example, instead of just saying 12 on food to know that it should be 8 on boar and 4 on berries. Maybe display this on hover ? Let me know what you think.

**Comment by CraftySalamander** [comment]
This feature could help a bit indeed, but it requires all the build orders to be updated accordingly.
I would like to keep their design easy for anybody to write his own BO, which will be difficult with this.

On top of that, this info should not be very useful when following the build order instructions, which should tell you how many villagers to put on each resource (but indeed, you cannot check if you did things correctly after a few steps).

Therefore, I prefer to not implement it. If you really want to see this information, you can add a line in the notes with the repartition between the food sources.

**Comment by CraftySalamander** [comment]
If you want to try it, feel free to go ;-)

You can fork the project and submit a pull request when it is working and clean.

It is important that it remains compatible with the normal BOs (food count represented as int).

Some hints:
* You must adapt [this check](https://github.com/CraftySalamander/RTS_Overlay/blob/master/aoe2/aoe2_build_order.py#L44)
* [target_food](https://github.com/CraftySalamander/RTS_Overlay/blob/master/aoe2/aoe2_game_overlay.py#L336) should become the sum of the elements if it is not an integer
* [get_mouse_label_id](https://github.com/CraftySalamander/RTS_Overlay/blob/master/common/label_display.py#L397) (applied on [self.build_order_resources](https://github.com/CraftySalamander/RTS_Overlay/blob/master/aoe2/aoe2_game_overlay.py#L366)) can be used to retrieve the ID of the label being hovered by the mouse. Find the one of the food resource, and open a hint window with the food repartition when receiving the IDs of the food.

If you need more help, feel free to ask :-)

**Comment by Gvanderl** [comment]
Hey, thanks for the advice.
I've made some good progress on the new feature (man PyQT can be hard to work with) and even added some optimisations. I'd like to add this to the project but I get an error when running `prepare_release.py`

```
Traceback (most recent call last):
  File "E:\PycharmProjects\RTS_Overlay\prepare_release.py", line 75, in <module>
    compile_clean(name_overlay='aoe2_overlay', game_folder='aoe2', out_lib_name=aoe2_library_name,
  File "E:\PycharmProjects\RTS_Overlay\prepare_release.py", line 40, in compile_clean
    os.rename(os.path.join(f'{name_overlay}.dist', f'{name_overlay}.exe'),
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'aoe2_overlay.dist\\aoe2_overlay.exe' -> 'aoe2_overlay.dist\\aoe2_overlay_with_console.exe'
```

This happens on both linux and windows, any idea of what's happening ?

**Comment by CraftySalamander** [comment]
First, do you manage to run the application with `python aoe2_overlay.py`?

If yes, I only tested the `prepare_release.py` script in Windows (but maybe it could work on Linux too).
Does the file being renamed in this function exist?

If yes, it is probably a permission problem. I had it once and discovered that my antivirus (BitDefender) was causing it... even if I generated this exe myself. I needed to add an exception for it.

**Comment by Gvanderl** [comment]
Yes, `python aoe2_overlay.py` runs.
I've tried on both windows and linux, and got the same error on both.
I don't think the file exists. I pulled the repo and did not get any .dist or .exe files. Not sure how I'm supposed to get those.

**Comment by CraftySalamander** [comment]
[This line](https://github.com/CraftySalamander/RTS_Overlay/blob/master/prepare_release.py#L36) is in charge of generating the exe.
If after this line, aoe2_overlay.exe was not created, then Nuitka encountered an issue.
Try to look for the error in the Nuitka console output.

In the worst case, I can create the python package myself (but only for Windows), after merge.

**Comment by Gvanderl** [comment]
I figured it out. `prepare_release.py` does not work on ubuntu but I managed to make it work on windows. 
I don't have the permissions to push my new branch though.

**Comment by CraftySalamander** [comment]
what you can do:
1. fork my project
2. create a new branch on your forked version
3. copy your changes and commit
4. create a pull request on my repo

**Comment by Gvanderl** [comment]
Yes, I do need to be able to push my branch in order to create a pull request though, which I am unauthorized to do at the moment.

**Comment by CraftySalamander** [comment]
Can you re-test?

**Comment by Gvanderl** [comment]
I keep getting

```
remote: Permission to CraftySalamander/RTS_Overlay.git denied to Gvanderl.
fatal: unable to access 'https://github.com/CraftySalamander/RTS_Overlay/': The requested URL returned error: 403
```

**Comment by CraftySalamander** [comment]
When looking at the forks of my project, I see only one fork and it is not from you. Are you sure you indeed forked the project?

**Comment by Gvanderl** [comment]
Ah I made a mistake there, my bad

**Comment by CraftySalamander** [comment]
I see your pull request, thanks. I will review it when I have time.
Note that I have a busy weekend in front of me, so you might have to wait a bit.

**Comment by CraftySalamander** [comment]
Nice work.
It works well. I already merged your pull request.
I will make a few modifications before preparing the release.

**Comment by Gvanderl** [comment]
That's great to hear ! I'm happy to have contributed.
