### ISSUE TITLE
Most of the build orders arent working from https://buildorderguide.com/

### ISSUE THREAD

**Issue by talibahmed11** [CraftySalamander/RTS_Overlay#13]
Most of the build order from the https://buildorderguide.com/ arent working. Also cannot figure out why, especially after looking at the code. For example this is a build order for 1Range archer that works.

{
    "name": "1Range Archers",
    "civilization": "Any",
    "author": "Hera",
    "source": "https://www.youtube.com/watch?v=KTUB-rASV7o&t=743s&ab_channel=Hera-AgeofEmpires2",
    "description": "Recommended Civs: Britons, Mayans, Ethiopians, Tatars, Vikings",
    "build_order": [
        {
            "villager_count": 6,
            "age": 1,
            "resources": {
                "wood": 0,
                "food": 6,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "2 @other/House_aoe2DE.png@ + 6 on @animal/Sheep_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 9,
            "age": 1,
            "resources": {
                "wood": 3,
                "food": 6,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "@lumber_camp/Lumber_camp_aoe2de.png@ + 3 on @resource/Aoe2de_wood.png@"
            ]
        },
        {
            "villager_count": 10,
            "age": 1,
            "resources": {
                "wood": 3,
                "food": 7,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "1 Lures @animal/Boar_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 11,
            "age": 1,
            "resources": {
                "wood": 3,
                "food": 8,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "@other/House_aoe2DE.png@ + @mill/Mill_aoe2de.png@ + 1 on @resource/BerryBushDE.png@",
                "Push 3 @animal/Deer_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 17,
            "age": 1,
            "resources": {
                "wood": 3,
                "food": 14,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "6 on @resource/Aoe2de_food.png@ Under @town_center/Towncenter_aoe2DE.png@",
                "Lure @animal/Boar_aoe2DE.png@ With @resource/MaleVillDE.jpg@ Under @town_center/Towncenter_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 19,
            "age": 1,
            "resources": {
                "wood": 5,
                "food": 14,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "2 on @resource/Aoe2de_wood.png@",
                "Research @town_center/LoomDE.png@",
                "Perfect time 7:05",
                "Research 20 Pop @age/FeudalAgeIconDE_alpha.png@"
            ]
        },
        {
            "villager_count": 19,
            "age": 2,
            "resources": {
                "wood": 12,
                "food": 4,
                "gold": 2,
                "stone": 0,
                "builder": 1
            },
            "notes": [
                "Before @age/FeudalAgeIconDE_alpha.png@",
                "5 @resource/Aoe2de_food.png@ Under @town_center/Towncenter_aoe2DE.png@ \u2192 5 @resource/Aoe2de_wood.png@ + @lumber_camp/Lumber_camp_aoe2de.png@",
                "2 @resource/Aoe2de_food.png@ Under @town_center/Towncenter_aoe2DE.png@ \u2192 2 Straggler Tree",
                "1 @resource/Aoe2de_food.png@ Under @town_center/Towncenter_aoe2DE.png@ \u2192 1 Builder + @other/House_aoe2DE.png@",
                "@barracks/Barracks_aoe2DE.png@",
                "2 @resource/Aoe2de_food.png@ Under @town_center/Towncenter_aoe2DE.png@ \u2192 2 Builders + @mining_camp/Mining_camp_aoe2de.png@",
                "2 Builders \u2192 2 @resource/Aoe2de_gold.png@"
            ]
        },
        {
            "villager_count": 19,
            "age": 2,
            "resources": {
                "wood": 12,
                "food": 4,
                "gold": 2,
                "stone": 0,
                "builder": 1
            },
            "notes": [
                "In @age/FeudalAgeIconDE_alpha.png@",
                "Research @lumber_camp/DoubleBitAxe_aoe2DE.png@",
                "@archery_range/Archery_range_aoe2DE.png@",
                "Start Training @archery_range/Archer_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 21,
            "age": 2,
            "resources": {
                "wood": 12,
                "food": 4,
                "gold": 4,
                "stone": 0,
                "builder": 1
            },
            "notes": [
                "2 on @resource/Aoe2de_gold.png@",
                "@blacksmith/Blacksmith_aoe2de.png@",
                "Research @blacksmith/FletchingDE.png@",
                "Train 1-4 Spearmen if enemy is pushing with @stable/Scoutcavalry_aoe2DE.png@",
                "4 @resource/Aoe2de_food.png@ Under @town_center/Towncenter_aoe2DE.png@ \u2192 4 @resource/BerryBushDE.png@",
                "Start making @mill/FarmDE.png@ as the @resource/Aoe2de_wood.png@ becomes available"
            ]
        }
    ]
}

But this build order which is similar doesnt.

{
    "name": "20 Elephants In 20 Minutes",
    "civilization": "Malay",
    "author": "Morley Games",
    "source": "https://www.youtube.com/watch?v=cTsjyfGzHuc",
    "description": "Make 20 elephants in 20 minutes.",
    "build_order": [
        {
            "villager_count": 6,
            "age": 1,
            "resources": {
                "wood": 0,
                "food": 6,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "2 @other/House_aoe2DE.png@ + 6 on @animal/Sheep_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 11,
            "age": 1,
            "resources": {
                "wood": 5,
                "food": 6,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "@other/House_aoe2DE.png@ + 5 on @resource/Aoe2de_wood.png@"
            ]
        },
        {
            "villager_count": 12,
            "age": 1,
            "resources": {
                "wood": 5,
                "food": 7,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "1 Lures @animal/Boar_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 15,
            "age": 1,
            "resources": {
                "wood": 5,
                "food": 10,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "1 Lures @animal/Boar_aoe2DE.png@ + 2 More on @animal/Boar_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 19,
            "age": 1,
            "resources": {
                "wood": 9,
                "food": 10,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "@other/House_aoe2DE.png@ + 4 on @resource/Aoe2de_wood.png@",
                "4 @animal/Boar_aoe2DE.png@ → 4 @animal/Deer_aoe2DE.png@",
                "@mill/Mill_aoe2de.png@"
            ]
        },
        {
            "villager_count": 25,
            "age": 1,
            "resources": {
                "wood": 9,
                "food": 16,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "2 @other/House_aoe2DE.png@ + 6 on @resource/BerryBushDE.png@"
            ]
        },
        {
            "villager_count": 29,
            "age": 1,
            "resources": {
                "wood": 13,
                "food": 16,
                "gold": 0,
                "stone": 0
            },
            "notes": [
                "4 on @resource/Aoe2de_wood.png@"
            ]
        },
        {
            "villager_count": 32,
            "age": 1,
            "resources": {
                "wood": 13,
                "food": 16,
                "gold": 3,
                "stone": 0
            },
            "notes": [
                "3 on @resource/Aoe2de_gold.png@",
                "Research 33 Pop @age/FeudalAgeIconDE_alpha.png@"
            ]
        },
        {
            "villager_count": 32,
            "age": 2,
            "resources": {
                "wood": 13,
                "food": 16,
                "gold": 3,
                "stone": 0
            },
            "notes": [
                "Before @age/FeudalAgeIconDE_alpha.png@",
                "@barracks/Barracks_aoe2DE.png@ + @other/House_aoe2DE.png@"
            ]
        },
        {
            "villager_count": 34,
            "age": 2,
            "resources": {
                "wood": 13,
                "food": 18,
                "gold": 3,
                "stone": 0
            },
            "notes": [
                "In @age/FeudalAgeIconDE_alpha.png@",
                "2 on @mill/FarmDE.png@",
                "2 @stable/Stable_aoe2DE.png@ + @blacksmith/Blacksmith_aoe2de.png@"
            ]
        },
        {
            "villager_count": 34,
            "age": 2,
            "resources": {
                "wood": 9,
                "food": 18,
                "gold": 7,
                "stone": 0
            },
            "notes": [
                "4 @resource/Aoe2de_wood.png@ → 4 @resource/Aoe2de_gold.png@"
            ]
        },
        {
            "villager_count": 34,
            "age": 2,
            "resources": {
                "wood": 9,
                "food": 16,
                "gold": 9,
                "stone": 0
            },
            "notes": [
                "2 @resource/BerryBushDE.png@ → 2 @resource/Aoe2de_gold.png@"
            ]
        },
        {
            "villager_count": 34,
            "age": 2,
            "resources": {
                "wood": 8,
                "food": 17,
                "gold": 9,
                "stone": 0
            },
            "notes": [
                "Seed 1 @mill/FarmDE.png@ with a Lumberjack",
                "Research @age/CastleAgeIconDE_alpha.png@"
            ]
        },
        {
            "villager_count": 34,
            "age": 3,
            "resources": {
                "wood": 8,
                "food": 17,
                "gold": 9,
                "stone": 0
            },
            "notes": [
                "In @age/CastleAgeIconDE_alpha.png@",
                "Continue adding new @resource/MaleVillDE.jpg@ to @mill/FarmDE.png@",
                "Train 20 @stable/Battle_elephant_aoe2DE.png@",
                "Research @stable/HusbandryDE.png@ + @blacksmith/ScaleBardingArmorDE.png@"
            ]
        }
    ]
}

Kind of losing my mind trying to figure out why. IDK for now I think ill just retype everything but if you could help it be nice. (I also tried alot of other build order from the website and most of them arent working)

**Comment by CraftySalamander** [comment]
Hi.
I just tested yout 2 BOs and they are both working fine.

The only difference is see between them is that your first BO is for a generic civ (`"civilization": "Any",`) and will be available when selecting any civilization, while your second BO is specific for the Malay (`"civilization": "Malay",`) and will thus only appear if you first select the Malay civilization on top of the search bar.

**Comment by CraftySalamander** [comment]
You can watch this video to have a full demo: https://youtu.be/hC7FMA6zgYo

**Comment by talibahmed11** [comment]
Wow, Thank you so much. I dont know why I didnt think of that. Makes sense for it to do it that way. Thank you so much again for making this and its super helpful!

**Comment by CraftySalamander** [comment]
You are welcome.
