### ISSUE TITLE
Won't Launch

### ISSUE THREAD

**Issue by Seannach** [CraftySalamander/RTS_Overlay#15]
I've downloaded, extracted, and attempted to launch the overlay .exe and the console version. I've set an exception in my virus protection. I can't seem to get it to launch. Any assistance would be greatly appreciated.

**Comment by CraftySalamander** [comment]
Could you test release 1.5.4: https://github.com/CraftySalamander/RTS_Overlay/releases/download/1.5.4/aoe2_overlay.zip

**Comment by Seannach** [comment]
That worked! Thanks very much!

**Comment by CraftySalamander** [comment]
You are welcome.

I think I detected the issue today in version 1.6.1.
I will correct it in version 1.6.2.

**Comment by CraftySalamander** [comment]
The bug should be solved now.

If you have time, could you also test version 1.6.2: https://github.com/CraftySalamander/RTS_Overlay/releases/download/1.6.2/aoe2_overlay.zip

**Comment by Seannach** [comment]
Works on my end!

**Comment by CraftySalamander** [comment]
Thanks for the bug report and the test, it helps a lot !
