### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Mario2280** [CraftySalamander/RTS_Overlay#17]
Trojan:Win32/Wacatac.B!ml??? on Win10 detected

**Comment by CraftySalamander** [comment]
Some antivirus softwares provide false positives when they see a zip file containing an exe compiled from python code.
We noticed that antivirus softwares started to generate more false positives in the last months.

You can have a look in the [Troubleshooting section](https://github.com/CraftySalamander/RTS_Overlay?tab=readme-ov-file#troubleshooting).

In short, you need to add an exception or run the code from python source (which is easy to do, some people without programming knowledge could do it).

I am thinking about some alternatives like a pure web based overlay, but I am not sure it is totally feasible, and that will still require months.

Could you also tell me which version you are using (the last one is 1.8.0).
