### ISSUE TITLE
To be able to use it on linux I have to run it as root

### ISSUE THREAD

**Issue by zrno** [CraftySalamander/RTS_Overlay#19]
To run your tool in python on linux I have to run it as root. Otherwise I get the error 

```
self.keyboard_mouse = KeyboardMouseManagement(print_unset=False)
...
...
raise ImportError('You must be root to use this library on linux.')
```

But when running it as root the main directory of the app changes to /root/...../ and adding build orders and similar doesn't work, or at least it only shows the 10 default build orders but doesn't show any others.

Would you consider replacing the KeyboardMouseManagement with something else like pynput?

**Comment by CraftySalamander** [comment]
Hi.
Thank you for the report.
Using another library (like `pynput`) could be an option for your problem.

However, I am currently developing other features and I do not have a Linux environment. If you are motivated, you can maybe update and test on a fork of the project, then open a pull request.

**Comment by CraftySalamander** [comment]
@zrno 
This should be solved in master, thanks to the PR from @stechermichal .
Could you test it (tip of master) when you have the time?

**Comment by CraftySalamander** [comment]
Closing the issue (should be solved and no answer for more than a month).
