### ISSUE TITLE
[Feature Request}

### ISSUE THREAD

**Issue by coreyjansen** [CraftySalamander/RTS_Overlay#2]
Would be nice for the ability to import from https://age4builder.com/ might be worth creating a pull request to build an API on age4builder to grab the build in json format. Is this something you have thought of?

**Comment by CraftySalamander** [comment]
Yes, I even wrote the code for it, see here: https://github.com/LENpolygon/Build-Order-Tool-AoE4-/pull/33
Waiting for LENpolygon answer.

**Comment by CraftySalamander** [comment]
This is now available on https://age4builder.com, closing the issue.
