### ISSUE TITLE
"cannot proceed because python38.dll was not found"

### ISSUE THREAD

**Issue by Jippi19** [CraftySalamander/RTS_Overlay#21]
Hello,

I have a problem when I try to launch the .exe.

I did follow the trouble shooting and unblock the zip folder but I still have the same error message.

I would really wish to avoid the python solution

**Comment by CraftySalamander** [comment]
This is strange. If you see this message, it means that it is not related to an antivirus blocking the exe.
Did you unblock the downloaded zip before doing anything else (unblocking it after extraction will not help) ?

Maybe re-download, unblock the newly download package and re-test.
Otherwise, I only see the python solution for now.

I plan to work on a web-based solution (which will not require installation), but it will still takes months.

**Comment by Jippi19** [comment]
HelloThanks for the reply!I did try unblock before and after but always same results.I will try the python but I'm so noob with those thing. I dont know anything about coding.Thanks! Le 7 avr. 2024 14 h 35, CraftySalamander ***@***.***> a écrit :
This is strange. If you see this message, it means that it is not related to an antivirus blocking the exe.
Did you unblock the downloaded zip before doing anything else (unblocking it after extraction will not help) ?
Maybe re-download, unblock the newly download package and re-test.
Otherwise, I only see the python solution for now.
I plan to work on a web-based solution (which will not require installation), but it will still takes months.

**Comment by CraftySalamander** [comment]
It is a pity.
I do not know if you saw the last video I shared, but I show the installation (part of it) [here](https://www.youtube.com/watch?v=qFBkpTnRzWQ&t=1059s).

`Le 7 avr. 2024 14 h 35, CraftySalamander ***@***.***> a écrit` You seem to be French speaker (like me), but from the time, I would guess that it is Canada ;-)

**Comment by Jippi19** [comment]
Yes I watch the entire video.Oui framcophone du Quebec. :) MerciLe 7 avr. 2024 15 h 04, CraftySalamander ***@***.***> a écrit :
It is a pity.
I do not know if you saw the last video I shared, but I show the installation (part of it) here.
Le 7 avr. 2024 14 h 35, CraftySalamander ***@***.***> a écrit You seem to be French speaker (like me), but from the time, I would guess that it is Canada ;-)

**Comment by CraftySalamander** [comment]
Closing the issue (no update for more than a month).
