### ISSUE TITLE
Empty search result recommendation

### ISSUE THREAD

**Issue by imartin22k** [CraftySalamander/RTS_Overlay#22]
It took me a while to figure out you needed to put a space into the search field to get all the build orders, so I recommend making everything show up when the search field is blank. I did see that in the README, but I grazed over it my first time through.

Everything else I've tried on this app is great though, appreciate the time you put into this!

**Comment by CraftySalamander** [comment]
Thank you for the feedback.
I can check for next releases if an indication could appear by default in the search bar.
I would prefer to avoid showing all the BOs by default, because it would take too much space when you have many BOs.

**Comment by imartin22k** [comment]
Yeah that makes sense, does Qt allow for grey text in the background of an empty entry field that says "Type space to see all build orders" or something? In general it would be nice when sorting by civ just to see all the options without having to type space, and due to the 10 max limit in the config it seems like it is not taking up too much space to me, but I get why you would want to reduce space it takes up at the same time.

**Comment by CraftySalamander** [comment]
I will add this for the next release
![image](https://github.com/CraftySalamander/RTS_Overlay/assets/103726735/4ed028af-5e85-4c0a-aaa6-000d02c3e351)

**Comment by imartin22k** [comment]
That seems like a great solution. This has been awesome to use so thanks again for making this!
