### ISSUE TITLE
I'm having trouble copying anything off of AoE4guides.  I hit the three dots and the overlay tool button, says it will copy to my clipboard, but then it doesn't copy anything. 

### ISSUE THREAD

**Issue by CrazedSadeyr** [CraftySalamander/RTS_Overlay#31]
Im not sure whats up with this or if its a bug but it simply doesn't work for me. : <

**Comment by CraftySalamander** [comment]
It is more a question for AoE4 Guides GitHub (link [here](https://github.com/jensbuehl/aoe4-guides/issues)), but I think I can answer.

Most likely, the copy to clipboard feature is blocked in your web browser.
An easy solution is to test with another web browser.
For instance, someone had the same issue with Firefox, then tested with Chrome and it worked.

**Comment by CrazedSadeyr** [comment]
Tysm this fixed it, I do indeed use firefox.  <3 Loving the work youve done, it has made learning more competitive gameplay a lot easier with poor memory and a single monitor x3

**Comment by CrazedSadeyr** [comment]
Tysm this fixed it, I do indeed use firefox. <3 Loving the work youve done, it has made learning more competitive gameplay a lot easier with poor memory and a single monitor x3

**Comment by CraftySalamander** [comment]
@jensbuehl FYI

**Comment by jensbuehl** [comment]
More info please.

Which browser?
Link to the BO that is not working?

Assumption: U are using Firefox or some other exotic browser. Firefox does not allow modifying the clipboard. This feature works only on chromium based browsers.

Workaround: Download as json file and move on from there.

Or use a browser that allows clipboard modifications.

**Comment by jensbuehl** [comment]
Ah, closed already. It's early in the morning here. 😉
I will try to hide the feature in future if not supported by the browser or at least give a hint what's going on.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jensbuehl** [comment]
https://github.com/jensbuehl/aoe4-guides/issues/103

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CrazedSadeyr** [comment]
@jensbuehl That makes sense, with firefox not allowing clipboard modifications being the reasoning.  Is there an easy method for downloading it as a json? There's a download option but it downloads a .bo file, is that the same thing or something I am doing wrong on my end?

**Comment by jensbuehl** [comment]
It's the same data. Just a different file extension.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CrazedSadeyr** [comment]
Oooh, I see.  I tried to put it into the RTS overlay and it wasn't working, but I might've been doing it wrong.  Ty for the info!

**Comment by jensbuehl** [comment]
Might be a different issue then.
If the problem persists, please share the BO that is not working so that crafty and I can reproduce.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CrazedSadeyr** [comment]
I went ahead and used a different browser to set it up, and it worked.  I'm not sure what the issue is specifically- I tried manually downloading another, put the .bo file in the same folder as the json to make sure, and it still didn't appear.  I might be doing it wrong, though, so I wouldn't put it past myself. x3

**Comment by jensbuehl** [comment]
I quickly double checked. It should also work with the downloaded file.

Have a nice day!

**Comment by CrazedSadeyr** [comment]
Tyvm for the help ^ ^

**Comment by CraftySalamander** [comment]
@CrazedSadeyr 
When you put the downloaded .bo file in RTS Overlay, do you use the EXE application or the web-based solution?
* For the web-based solution, you should be able to drag and drop it on the main panel of https://rts-overlay.github.io/ (Select first `Age of Empires IV`, again not sure if it works with Firefox).
* For the EXE solution, RTS Overlay is only looking for files with the `.json` extension. So, you will need to update the name to change the extension to `.json` (@jensbuehl Maybe it would be better for *aoe4guides* to output a file with extension `.json` instead of `.bo`).

**Comment by jensbuehl** [comment]
I meant pasting the content, not the file itself.
But you are right. Will update in future versions accordingly.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CrazedSadeyr** [comment]
@CraftySalamander 

Sorry for not replying to this sooner, I got busy with work and didn't even notice the response!

I use the .exe and I hadn't thought about opening up the .bo or changing it into a json myself.  Fixed the situation, thank you for the help ^ ^
