### ISSUE TITLE
Duplicate build order names

### ISSUE THREAD

**Issue by ebodur20** [CraftySalamander/RTS_Overlay#5]
When there is more than 1 build order with the same name, RTS_Overlay shows the first (Usually Abbasid in this case) build order it finds in the Build Order view, regardless of which civilization was selected.

This can be tested by creating 2x build orders with the same name (e.g. Beastyqt S2 - 2 town centers, 1 for French, 1 for Abbasid). Even if French is selected, the tool shows the Abbasid build order with the same name).

**Comment by CraftySalamander** [comment]
Thank you for the report, it is solved in the commit [d088178c03adc2e3c39e332aae2f6547131baeda](https://github.com/CraftySalamander/RTS_Overlay/commit/d088178c03adc2e3c39e332aae2f6547131baeda).

It will be released with version 1.4.2 (here are the features coming with this version):
```
* Keyboard and mouse hotkeys:
    * 'Esc' can be used to cancel a hotkey configuration.
    * Keyboard and mouse can be used as a combined hotkey (e.g. Ctrl+extra button 1).
    * Mouse inputs can be configured in the hotkeys panel.
* AoE4
    * Malians and Ottomans added.
    * Updated for Season 3 (naval units...).
    * Correct bug related to build orders with the same name.
```

**Comment by CraftySalamander** [comment]
Btw, I could see that you wrote a lot of BOs in https://age4builder.com, thank you for the contributions :-)

**Comment by ebodur20** [comment]
Hi!
Indeed. I used your core builds as a template and updated / revised them. I am trying to use same 'language' / structure in new ones.I am planning to add more over time (mostly for Beasty's guides... but will likely extend it to others over time). Thanks!
    Op dinsdag 1 november 2022 om 10:44:17 CET schreef CraftySalamander ***@***.***>:  
 
 


Btw, I could see that you wrote a lot of BOs in https://age4builder.com, thank you for the contributions :-)

**Comment by CraftySalamander** [comment]
Hi @ebodur20 
I just uploaded version 1.4.2.
When you have time, could you test it (you only need to use the new downloaded folder: your settings are saved on your computer)?
Could you check if this issue is solved on your side (+ you can also check the new keyboard+mouse hotkey configuration if you want)?
Thank you.

**Comment by ebodur20** [comment]
mouse hotkeys seem to be working. also, the same name build order issue appears also fixed. thank you!
    Op dinsdag 1 november 2022 om 14:27:19 CET schreef CraftySalamander ***@***.***>:  
 
 


Hi @ebodur20
I just uploaded version 1.4.2.
When you have time, could you test it (you only need to use the new downloaded folder: your settings are saved on your computer)?
Could you check if this issue is solved on your side (+ you can also check the new keyboard+mouse hotkey configuration if you want)?
Thank you.

**Comment by CraftySalamander** [comment]
Great! Closing the issue then.
