### ISSUE TITLE
ag4builder.com images not converting to JSON with the "salamander" copy to clipboard tool

### ISSUE THREAD

**Issue by Big-Pharma** [CraftySalamander/RTS_Overlay#8]
hello, I've been using the aoe4 overlay and before asking my question I'd like to say thank you for making yourself available to answer questions... Recently, I've had an issue getting properly coded .json file from age4builders salamander copy tool, the structure of the code is correct and the text is generally present but none of the images fetch orders "@/.png@" are present. For that reason I have been just copy/pasting the image fetch orders into the pre-structured json. It's worked alright but is extremely time consuming. So I guess my question is, is an easier way to fix this other than essentially learning to code as I am not very fast lol or possibly a different builder tool available that can transfer the image fetch orders (i.e. villiger image = @unit_worker/villager.png@). your input's appreciated, thank you.

I sent this message to Maguro on discord, he advised me to reach out to you through this medium.

**Comment by Big-Pharma** [comment]
wow, didn't expect such a speedy response. Mario must have really loved Peach because I'm only on the 3rd castle and I'm already thinking of finding a new princess, lol... 

I have experienced your bug as well, with the "/n"... I would gladly share the build order with you except sadly, I didn't save it to url before accidentally using that tab for a google search (would never tell someone how to do something I couldn't do myself, but that auto save function on google docs/sheets saves 1,000s of people their jobs every year LOL) and have since spent quite a while messing with the text in JSON since receiving it from the tool, so I don't think it would be an ample example anymore...  Similar things happened in bits and pieces before that's how I got more acquainted with the JSON in general (I have little to no coding experience, general knowledge, general exposure very tertiary to say the least), from looking at the JSON and the files on my computer I gathered it was just instructing the program to locate an image and display it in the text box, so I figured out the instructions for the missing pictures and inserted them. yesterday/today is the first time its ever just ignored all images. As I said I don't have the original anymore and I only found this because I was trying to get a list of all the image tags to fix broken BO's when they happen, so I put in one of every image and got the base structure JSON (HUGE LET DOWN LOL, proceeded to type out the ones I used the most) but for example if I go to the tool right now put a couple pictures in hit the salamander logo I get this 


    "civilization": "Holy Roman Empire",
    "name": "Infantry, Religion and Defense",
    "author": "unknown",
    "source": "unknown",
    "build_order": [
        {
            "age": -1,
            "population_count": -1,
            "time": "0",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                "    "
            ]
        },
        {
            "age": -1,
            "population_count": -1,
            "time": "1",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                ""
            ]
        },
        {
            "age": -1,
            "population_count": -1,
            "time": "2",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                ""
            ]
        }
    ]
}

if I add text with photos?

{
    "civilization": "Holy Roman Empire",
    "name": "Infantry, Religion and Defense",
    "author": "unknown",
    "source": "unknown",
    "build_order": [
        {
            "age": -1,
            "population_count": -1,
            "time": "0",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                "     If I add text with photos?"
            ]
        },
        {
            "age": -1,
            "population_count": -1,
            "time": "1",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                ""
            ]
        },
        {
            "age": -1,
            "population_count": -1,
            "time": "2",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                ""
            ]
        }
    ]
}

I'm about 50% of the way to just spending the next 3-6 months teaching myself to code just this function, mainly just because I see that pop count is able to be included in the overlay program and for some reason it and the age columns aren't included in the builder tool and now that I've added it to some of my BO's I don't want to have to manually adjust every JSON but I also can't go back lol. 

Thank you for your work making this tool available, as well as pointing me in the right direction it's appreciated.

**Comment by Big-Pharma** [comment]
{
    "civilization": "Holy Roman Empire",
    "name": "Infantry, Religion and Defense",
    "author": "unknown",
    "source": "unknown",
    "build_order": [
        {
            "age": -1,
            "population_count": -1,
            "time": "0",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                "    "
            ]
        },
        {
            "age": -1,
            "population_count": -1,
            "time": "1",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                ""
            ]
        },
        {
            "age": -1,
            "population_count": -1,
            "time": "2",
            "villager_count": -1,
            "resources": {
                "food": -1,
                "wood": -1,
                "gold": -1,
                "stone": -1
            },
            "notes": [
                ""
            ]
        }
    ]
}

**Comment by CraftySalamander** [comment]
I am not sure I understand exactly your question, but you can find the full doc of the JSON format in the Readme of this project (RTS Overlay): https://github.com/CraftySalamander/RTS_Overlay/blob/master/Readme.md

In case you are wondering what is the difference between RTS Overlay and AoE4 Overlay: RTS Overlay is the tool that I developed, mainly for BOs. AoE4 Overlay is the tool from Maguro that he developed mainly for match stats.
In order to avoid splitting the AoE4 community between these 2 tools, I ported the BOs code of RTS Overlay to AoE4 Overlay.
In short, they use the same JSON format because they run the same code.

To design a JSON, you can start from one of the templates [here](https://github.com/CraftySalamander/RTS_Overlay/tree/master/build_orders/aoe4) and adapt it to your needs.
The fields with a value are self-explanatory (they are ignored when setting a value of -1). Time is just a string.
The notes can include images by putting them between @@, and writing the image with its path relative to [this folder](https://github.com/CraftySalamander/RTS_Overlay/tree/master/pictures/aoe4), like @building_economy/market.png@.

**Comment by CraftySalamander** [comment]
FYI, a new BO website with overlay export feature is available: https://aoe4guides.com
